# Generated by Django 6.0.4 on 2026-04-21 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_realestateagent_delete_brokeroffice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_code', models.CharField(db_index=True, max_length=10, verbose_name='시군구코드')),
                ('ld_code_nm', models.CharField(max_length=100, verbose_name='시군구명')),
                ('jurirno', models.CharField(db_index=True, max_length=50, verbose_name='등록번호')),
                ('bsnm_cmpnm', models.CharField(max_length=200, verbose_name='사업자상호')),
                ('brkr_nm', models.CharField(db_index=True, max_length=100, verbose_name='중개업자명')),
                ('brkr_asort_code', models.CharField(choices=[('1', '중개인'), ('2', '중개법인'), ('9', '기타')], max_length=5, verbose_name='중개업자종별코드')),
                ('brkr_asort_code_nm', models.CharField(max_length=50, verbose_name='중개업자종별명')),
                ('crqfc_no', models.CharField(blank=True, max_length=50, verbose_name='자격증번호')),
                ('crqfc_acqdt', models.DateField(blank=True, null=True, verbose_name='자격증취득일')),
                ('ofcps_se_code', models.CharField(choices=[('01', '대표'), ('02', '소속'), ('99', '기타')], max_length=5, verbose_name='직위구분코드')),
                ('ofcps_se_code_nm', models.CharField(max_length=50, verbose_name='직위구분명')),
                ('last_updt_dt', models.DateField(blank=True, null=True, verbose_name='데이터기준일자')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '중개업자',
                'db_table': 'broker',
                'ordering': ['ld_code', 'brkr_nm'],
            },
        ),
        migrations.CreateModel(
            name='BrokerOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_code', models.CharField(db_index=True, max_length=10, verbose_name='시군구코드')),
                ('ld_code_nm', models.CharField(max_length=100, verbose_name='시군구명')),
                ('jurirno', models.CharField(max_length=50, unique=True, verbose_name='등록번호')),
                ('bsnm_cmpnm', models.CharField(db_index=True, max_length=200, verbose_name='사업자상호')),
                ('brkr_nm', models.CharField(db_index=True, max_length=100, verbose_name='중개업자명')),
                ('sttus_se_code', models.CharField(choices=[('1', '영업중'), ('2', '폐업'), ('3', '휴업')], db_index=True, default='1', max_length=5, verbose_name='상태구분코드')),
                ('sttus_se_code_nm', models.CharField(max_length=50, verbose_name='상태구분명')),
                ('regist_de', models.DateField(blank=True, null=True, verbose_name='등록일자')),
                ('estbs_begin_de', models.DateField(blank=True, null=True, verbose_name='보증설정시작일')),
                ('estbs_end_de', models.DateField(blank=True, null=True, verbose_name='보증설정종료일')),
                ('last_updt_dt', models.DateField(blank=True, null=True, verbose_name='데이터기준일자')),
                ('mnnmadr', models.CharField(blank=True, max_length=300, verbose_name='지번주소')),
                ('rdnmadr', models.CharField(blank=True, max_length=300, verbose_name='도로명주소')),
                ('rdnmadrcode', models.CharField(blank=True, max_length=30, verbose_name='도로명주소코드')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '중개업사무소',
                'db_table': 'broker_office',
                'ordering': ['-regist_de', 'ld_code'],
            },
        ),
        migrations.DeleteModel(
            name='RealEstateAgent',
        ),
        migrations.AddIndex(
            model_name='brokeroffice',
            index=models.Index(fields=['ld_code', 'sttus_se_code'], name='idx_office_ld_sttus'),
        ),
        migrations.AddIndex(
            model_name='brokeroffice',
            index=models.Index(fields=['bsnm_cmpnm'], name='idx_office_bsnm'),
        ),
        migrations.AddIndex(
            model_name='brokeroffice',
            index=models.Index(fields=['estbs_end_de'], name='idx_office_estbs_end'),
        ),
        migrations.AddField(
            model_name='broker',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to='brokers.brokeroffice'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['brkr_nm'], name='idx_broker_name'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['ofcps_se_code'], name='idx_broker_ofcps'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['crqfc_acqdt'], name='idx_broker_acqdt'),
        ),
        migrations.AlterUniqueTogether(
            name='broker',
            unique_together={('jurirno', 'brkr_nm', 'ofcps_se_code')},
        ),
    ]
