# Generated by Django 6.0.4 on 2026-04-28 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0004_ebbrokerinfo_realestateagent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brokers/%Y/%m/', verbose_name='이미지')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='사진 설명')),
                ('is_primary', models.BooleanField(default=False, verbose_name='대표이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='brokers.realestateagent', verbose_name='중개업소')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '중개업소 이미지',
                'verbose_name_plural': '중개업소 이미지 목록',
                'db_table': 'broker_image',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
    ]
