# Generated by Django 6.0.4 on 2026-05-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='리뷰 이미지'),
        ),
    ]
