# Generated by Django 6.0.4 on 2026-05-20 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField(verbose_name='대상 ID')),
                ('method', models.CharField(choices=[('keyword', '키워드 사전'), ('ai', 'AI 모델'), ('hybrid', '하이브리드')], default='keyword', max_length=20, verbose_name='분석 방식')),
                ('score', models.FloatField(verbose_name='종합 점수')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='위험 신호')),
                ('ai_probability', models.FloatField(blank=True, null=True, verbose_name='AI 긍정 확률(0~1)')),
                ('confidence', models.FloatField(default=0.0, verbose_name='결과 확신도(0~1)')),
                ('positive_hits', models.JSONField(blank=True, default=list, verbose_name='긍정 매칭')),
                ('negative_hits', models.JSONField(blank=True, default=list, verbose_name='부정 매칭')),
                ('danger_hits', models.JSONField(blank=True, default=list, verbose_name='위험 매칭')),
                ('needs_review', models.BooleanField(default=False, verbose_name='사람 검수 필요')),
                ('reviewed', models.BooleanField(default=False, verbose_name='검수 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='분석 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='대상 모델 종류')),
            ],
            options={
                'verbose_name': '감정분석 결과',
                'verbose_name_plural': '감정분석 결과 목록',
                'db_table': 'sentiment_result',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='idx_sentiment_target'), models.Index(fields=['is_dangerous', 'needs_review'], name='idx_sentiment_flag')],
            },
        ),
    ]
