# Generated by Django 4.2.11 on 2026-05-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentresult',
            name='label',
            field=models.CharField(choices=[('positive', '긍정'), ('neutral', '중립'), ('negative', '부정'), ('error', '분석 실패')], default='neutral', max_length=20, verbose_name='감정 라벨'),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='model_version',
            field=models.CharField(blank=True, default='', help_text='어느 분석기로 만든 결과인지 추적용 (예: dummy-v0, klue-bert-v1)', max_length=50, verbose_name='모델 버전'),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict, help_text='FastAPI 원본 JSON 응답 백업 (디버깅·재현용)', verbose_name='원본 응답'),
        ),
    ]
