# Generated by Django 6.0.4 on 2026-05-15 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('category', models.CharField(choices=[('latest', '최신글'), ('hot', '인기글'), ('region', '관심동네')], default='latest', max_length=20, verbose_name='카테고리')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='좋아요수')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '커뮤니티 글',
                'verbose_name_plural': '커뮤니티 글 목록',
                'db_table': 'community_post',
                'ordering': ['-created_at'],
            },
        ),
    ]
