# Generated by Django 6.0.4 on 2026-05-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='입력 시 이 닉네임으로 표시. 비우면 회원 username 사용.', max_length=30, verbose_name='익명 닉네임'),
        ),
    ]
