# Generated by Django 6.0.4 on 2026-04-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='시군구코드')),
                ('ld_code_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='시군구명')),
                ('jurirno', models.CharField(max_length=100, unique=True, verbose_name='등록번호')),
                ('bsnm_cmpnm', models.CharField(blank=True, max_length=255, null=True, verbose_name='사업자상호')),
                ('brkr_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='중개업자명')),
                ('sttus_se_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='상태구분코드')),
                ('sttus_se_code_nm', models.CharField(blank=True, max_length=50, null=True, verbose_name='상태구분명')),
                ('regist_de', models.DateField(blank=True, null=True, verbose_name='등록일자')),
                ('estbs_begin_de', models.DateField(blank=True, null=True, verbose_name='보증설정시작일')),
                ('estbs_end_de', models.DateField(blank=True, null=True, verbose_name='보증설정종료일')),
                ('last_updt_dt', models.DateField(blank=True, null=True, verbose_name='데이터기준일자')),
                ('mnnmadr', models.CharField(blank=True, max_length=255, null=True, verbose_name='지번주소')),
                ('rdnmadr', models.CharField(blank=True, max_length=255, null=True, verbose_name='도로명주소')),
                ('rdnmadr_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='도로명주소코드')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='원본응답데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '부동산중개업사무소',
                'verbose_name_plural': '부동산중개업사무소 목록',
                'ordering': ['-updated_at'],
            },
        ),
    ]
