# Generated by Django 6.0.4 on 2026-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_broker_brokeroffice_delete_realestateagent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBBrokerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_code', models.CharField(db_index=True, max_length=10, verbose_name='시군구코드')),
                ('ld_code_nm', models.CharField(blank=True, default='', max_length=100, verbose_name='시군구명')),
                ('jurirno', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='등록번호')),
                ('bsnm_cmpnm', models.CharField(blank=True, default='', max_length=200, verbose_name='사업자상호')),
                ('brkr_nm', models.CharField(blank=True, default='', max_length=100, verbose_name='중개업자명')),
                ('brkr_asort_code', models.CharField(blank=True, default='', max_length=10, verbose_name='중개업자종별코드')),
                ('brkr_asort_code_nm', models.CharField(blank=True, default='', max_length=50, verbose_name='중개업자종별명')),
                ('crqfc_no', models.CharField(blank=True, default='', max_length=50, verbose_name='자격증번호')),
                ('crqfc_acqdt', models.DateField(blank=True, null=True, verbose_name='자격증취득일')),
                ('ofcps_se_code', models.CharField(blank=True, default='', max_length=10, verbose_name='직위구분코드')),
                ('ofcps_se_code_nm', models.CharField(blank=True, default='', max_length=50, verbose_name='직위구분명')),
                ('last_updt_dt', models.DateField(blank=True, null=True, verbose_name='데이터기준일자')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
            ],
            options={
                'verbose_name': '부동산중개업자정보',
                'verbose_name_plural': '부동산중개업자정보 목록',
                'db_table': 'eb_broker_info',
            },
        ),
        migrations.CreateModel(
            name='RealEstateAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_code', models.CharField(max_length=10, verbose_name='시군구코드')),
                ('ld_code_nm', models.CharField(max_length=50, verbose_name='시군구명')),
                ('jurirno', models.CharField(max_length=20, unique=True, verbose_name='등록번호')),
                ('bsnm_cmpnm', models.CharField(max_length=100, verbose_name='사업자상호')),
                ('brkr_nm', models.CharField(max_length=50, verbose_name='중개업자명')),
                ('sttus_se_code', models.CharField(max_length=5, verbose_name='상태구분코드')),
                ('sttus_se_code_nm', models.CharField(max_length=20, verbose_name='상태구분명')),
                ('regist_de', models.DateField(verbose_name='등록일자')),
                ('estbs_begin_de', models.DateField(blank=True, null=True, verbose_name='보증설정시작일')),
                ('estbs_end_de', models.DateField(blank=True, null=True, verbose_name='보증설정종료일')),
                ('last_updt_dt', models.DateField(verbose_name='데이터기준일자')),
                ('mnnmadr', models.CharField(blank=True, max_length=200, verbose_name='지번주소')),
                ('rdnmadr', models.CharField(blank=True, max_length=200, verbose_name='도로명주소')),
                ('rdnmadr_code', models.CharField(blank=True, max_length=25, verbose_name='도로명주소코드')),
            ],
            options={
                'verbose_name': '부동산 중개업소',
                'verbose_name_plural': '부동산 중개업소 목록',
                'db_table': 'real_estate_agent',
                'ordering': ['-regist_de'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='broker',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='broker',
            name='idx_broker_name',
        ),
        migrations.RemoveIndex(
            model_name='broker',
            name='idx_broker_ofcps',
        ),
        migrations.RemoveIndex(
            model_name='broker',
            name='idx_broker_acqdt',
        ),
        migrations.RemoveIndex(
            model_name='brokeroffice',
            name='idx_office_ld_sttus',
        ),
        migrations.RemoveIndex(
            model_name='brokeroffice',
            name='idx_office_bsnm',
        ),
        migrations.RemoveIndex(
            model_name='brokeroffice',
            name='idx_office_estbs_end',
        ),
        migrations.AddIndex(
            model_name='ebbrokerinfo',
            index=models.Index(fields=['ld_code', 'brkr_nm'], name='idx_broker_code_name'),
        ),
        migrations.AddIndex(
            model_name='ebbrokerinfo',
            index=models.Index(fields=['bsnm_cmpnm'], name='idx_broker_company'),
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
        migrations.DeleteModel(
            name='BrokerOffice',
        ),
    ]
