# Generated by Django 6.0.4 on 2026-04-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0005_brokerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateagent',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='realestateagent',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
    ]
