# Generated by Django 6.0.4 on 2026-05-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0006_realestateagent_lat_realestateagent_lng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrokerImage',
        ),
    ]
