# Generated by Django 6.0.4 on 2026-05-19 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0002_review_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='대상 PK')),
                ('image', models.ImageField(upload_to='images/%Y/%m/', verbose_name='이미지')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('is_primary', models.BooleanField(default=False, verbose_name='대표 이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='대상 모델')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '이미지',
                'verbose_name_plural': '이미지 목록',
                'db_table': 'interactions_image',
                'ordering': ['-is_primary', '-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_image_target')],
            },
        ),
    ]
