# Generated by Django 6.0.4 on 2026-05-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_image'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='image',
            new_name='interaction_content_eb7998_idx',
            old_name='idx_image_target',
        ),
    ]
