# Generated by Django 6.0.4 on 2026-05-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_rename_idx_image_target_interaction_content_eb7998_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
